# Entregable 3

In [27]:
import numpy as np
import pandas as pd
import io

from bs4 import BeautifulSoup as bs
import requests

## 🎈 1. Ejercicio: Arkansas 🎈

Queremos obtener de la página de Wikipedia de "Arkansas", https://es.wikipedia.org/wiki/Arkansas, la tabla que nos indica la composición étnica a aprtir del censo de EEUU de 2020.

- Revisar la página web de Wikipedia y obtener la tabla en un df
- Sobre el df: revisar qué tipo de columnas tenemos y que valores contienen las mismas
- Renombrar las columnas a nombres más descriptivos
- Eliminar columnas que no sean necesarias
- Cambiar a tipo numérico (realizando los cambios necesarios, %) las columnas que contienen números
- **Realizar un análisis exploratorio sobre la tabla**

In [4]:
url = 'https://es.wikipedia.org/wiki/Arkansas'

In [5]:
tablas = pd.read_html(url)

for i, t in enumerate(tablas):
    print(f"Tabla {i}:\n", t.head(), "\n")

HTTPError: HTTP Error 403: Forbidden

In [6]:
# URL de Wikipedia
url = 'https://es.wikipedia.org/wiki/Arkansas'

# Simulamos un navegador para evitar el error 403
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) '
                  'AppleWebKit/537.36 (KHTML, like Gecko) '
                  'Chrome/123.0 Safari/537.36'
}

# Realizar la solicitud GET con el User-Agent especificado
response = requests.get(url, headers=headers)

In [7]:
print(f"response: {response}")
print(f"response.status_code: {response.status_code}")

response: <Response [200]>
response.status_code: 200

In [8]:
type(response.text)

str

In [9]:
# Verificar si la solicitud fue exitosa
if response.status_code == 200:
    # Utilizar pandas.read_html para extraer la tabla de la respuesta HTML
    tables = pd.read_html(response.text)
    print(f"El número de tablas encontradas: {len(tables)} \n\n")
else:
    print(f"Error: {response.status_code}")

El número de tablas encontradas: 7

/tmp/ipykernel_22592/2768303041.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(response.text)

In [10]:
io.StringIO(response.text)

In [11]:
# URL de Wikipedia
url = 'https://es.wikipedia.org/wiki/Arkansas'

# Simulamos un navegador para evitar el error 403
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) '
                  'AppleWebKit/537.36 (KHTML, like Gecko) '
                  'Chrome/123.0 Safari/537.36'
}

# Realizar la solicitud GET con el User-Agent especificado
response = requests.get(url, headers=headers)

if response.status_code == 200:
    # Convertir el HTML en un archivo de html
    html_content = io.StringIO(response.text)

    # Extraer tablas sin warning
    tables = pd.read_html(html_content)

    print(f"El número de tablas encontradas: {len(tables)} \n")
else:
    print(f"Error: {response.status_code}")

El número de tablas encontradas: 7

In [12]:
type(tables)

list

In [13]:
# Mostramos la primera tabla
display(tables[0].head())

,Arkansas State of Arkansas,Arkansas State of Arkansas.1,Arkansas State of Arkansas.2
0,Estado federado,Estado federado,Estado federado
1,Bandera Escudo,Bandera Escudo,Bandera Escudo
2,Bandera,Escudo,NaN
3,"Otros nombres: The Natural State, Land of Oppo...","Otros nombres: The Natural State, Land of Oppo...","Otros nombres: The Natural State, Land of Oppo..."
4,Lema: En latín: Regnat populus (En español: E...,Lema: En latín: Regnat populus (En español: E...,Lema: En latín: Regnat populus (En español: E...

Como hay 7 tablas, vamos a proceder a buscar la tabla que contiene la información de la composición étnica que nos pide el ejercicio. Echamos un vistazo previo a la página web solicitada para saber qué terminos podemos aplicar para encontrar la tabla que necesitamos. En este caso, sabemos que debe contener el término 'Raza'

In [14]:
url = 'https://es.wikipedia.org/wiki/Juegos_Ol%C3%ADmpicos'

# Simulamos un navegador para evitar el error 403
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) '
                  'AppleWebKit/537.36 (KHTML, like Gecko) '
                  'Chrome/123.0 Safari/537.36'
}

# Realizar la solicitud GET con el User-Agent especificado
response = requests.get(url, headers=headers)

if response.status_code == 200:
    # Convertir el HTML en un archivo de html
    html_content = io.StringIO(response.text)

    # Extraer tablas sin warning
    # # Filtramos las tablas que contienen el texto "Raza" en el encabezado
    tables = pd.read_html(html_content, match='Raza')

    print(f"El número de tablas encontradas: {len(tables)} \n")
else:
    print(f"Error: {response.status_code}")

ValueError: No tables found matching pattern 'Raza'

In [15]:
#Como nos da error con varias palabras, haremos la búsqueda de la tabla de forma manual

display(tables[4].head())

          Raza y etnia[11]​  Alone  Alone.1  Total  Total.1
0         Blanco no hispano  68.5%      NaN  73.2%      NaN
1                    Negros  14.9%      NaN  16.2%      NaN
2  Hispanios o Latinos[12]​      —      NaN   8.5%      NaN
3                 Asiáticos   1.7%      NaN   2.2%      NaN
4                   Nativos   0.7%      NaN   3.4%      NaN

In [16]:
#Convertimos a dataframe para poder trabajar con los datos

df = tables[4]
df

                           Raza y etnia[11]​  Alone  Alone.1  Total  Total.1
0                          Blanco no hispano  68.5%      NaN  73.2%      NaN
1                                     Negros  14.9%      NaN  16.2%      NaN
2                   Hispanios o Latinos[12]​      —      NaN   8.5%      NaN
3                                  Asiáticos   1.7%      NaN   2.2%      NaN
4                                    Nativos   0.7%      NaN   3.4%      NaN
5  Estadounidenses de las islas del Pacífico   0.5%      NaN   0.6%      NaN
6                                       Otro   0.3%      NaN   1.1%      NaN

In [17]:
#Comprobamos el tipo de datos que tenemos en el df

df.dtypes

Raza y etnia[11]​     object
Alone                 object
Alone.1              float64
Total                 object
Total.1              float64
dtype: object

In [19]:
#Eliminamos las columnas sin información

df_1 = df.drop(columns=['Alone.1', 'Total.1'])
df_1

                           Raza y etnia[11]​  Alone  Total
0                          Blanco no hispano  68.5%  73.2%
1                                     Negros  14.9%  16.2%
2                   Hispanios o Latinos[12]​      —   8.5%
3                                  Asiáticos   1.7%   2.2%
4                                    Nativos   0.7%   3.4%
5  Estadounidenses de las islas del Pacífico   0.5%   0.6%
6                                       Otro   0.3%   1.1%

In [20]:
#Renombramos las columnas para que sean más claras

df_1 = df_1.rename(columns={
    'Raza y etnia[11]​': 'etnia',
    'Alone': 'porcentaje'
})

In [21]:
df_1

                                       etnia porcentaje  Total
0                          Blanco no hispano      68.5%  73.2%
1                                     Negros      14.9%  16.2%
2                   Hispanios o Latinos[12]​          —   8.5%
3                                  Asiáticos       1.7%   2.2%
4                                    Nativos       0.7%   3.4%
5  Estadounidenses de las islas del Pacífico       0.5%   0.6%
6                                       Otro       0.3%   1.1%

In [22]:
#Realizamos un análisis exploratorio

df_1.describe()

                    etnia porcentaje  Total
count                   7          7      7
unique                  7          7      7
top     Blanco no hispano      68.5%  73.2%
freq                    1          1      1

In [23]:
#Como el anterior código nos ha arrojado resultados inesperados, volvemos a comprobar los datos

df_1.dtypes

etnia         object
porcentaje    object
Total         object
dtype: object

In [24]:
#Transformamos a float

df_1['porcentaje'] = (
    df_1['porcentaje']
    .str.replace('%','', regex=False)
    .str.replace(',','.', regex=False)
    .str.replace('—','', regex=False)
    .str.strip()
    .replace('', None)
    .astype(float)
)

df_1['Total'] = (
    df_1['Total']
    .str.replace('%','', regex=False)
    .str.replace(',','.', regex=False)
    .str.replace('—','', regex=False)
    .str.strip()
    .replace('', None)
    .astype(float)
)

In [25]:
df_1.dtypes

etnia          object
porcentaje    float64
Total         float64
dtype: object

In [26]:
df_1[['porcentaje','Total']].describe()

       porcentaje      Total
count    6.000000   7.000000
mean    14.433333  15.028571
std     27.085248  26.235772
min      0.300000   0.600000
25%      0.550000   1.650000
50%      1.200000   3.400000
75%     11.600000  12.350000
max     68.500000  73.200000

La tabla inicial recogida de Wikipedia ya nos da los datos ordenados que nos muestran que la etnia dominante es la 'Blanco no hispano', con un 73%, seguida de los 'Negros' con un 16%.

## 🎈 2. Ejercicio pandas 🎈

- Pandas: scrapear la tabla que contiene informacion sobre los álbums más vendidos por año en todo el mundo (https://es.wikipedia.org/wiki/Anexo:%C3%81lbumes_musicales_m%C3%A1s_vendidos) generando un dataframe con la información del año, nombre del álbum, artista y ventas. Ésta ultima columna deberá tener sus valores en numeros enteros en millones.

In [40]:
url = 'https://es.wikipedia.org/wiki/Anexo:%C3%81lbumes_musicales_m%C3%A1s_vendidos)'

In [41]:
tablas = pd.read_html(url)

for i, t in enumerate(tablas):
    print(f"Tabla {i}:\n", t.head(), "\n")

HTTPError: HTTP Error 403: Forbidden

In [46]:
# URL de Wikipedia
url = 'https://es.wikipedia.org/wiki/Anexo:%C3%81lbumes_musicales_m%C3%A1s_vendidos)'
# Simulamos un navegador para evitar el error 403
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) '
                  'AppleWebKit/537.36 (KHTML, like Gecko) '
                  'Chrome/123.0 Safari/537.36'
}

# Realizar la solicitud GET con el User-Agent especificado
response = requests.get(url, headers=headers)

In [47]:
print(f"response: {response}")
print(f"response.status_code: {response.status_code}")

response: <Response [404]>
response.status_code: 404

Como nos da el código 404, vamos a probar a cambiar la url por la actual

In [49]:
# URL de Wikipedia
url = 'https://es.wikipedia.org/wiki/Anexo:%C3%81lbumes_musicales_m%C3%A1s_vendidos#%C3%81lbum_m%C3%A1s_vendido_por_a%C3%B1o_en_todo_el_mundo'

# Simulamos un navegador para evitar el error 403
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) '
                  'AppleWebKit/537.36 (KHTML, like Gecko) '
                  'Chrome/123.0 Safari/537.36'
}

# Realizar la solicitud GET con el User-Agent especificado
response = requests.get(url, headers=headers)

In [50]:
print(f"response: {response}")
print(f"response.status_code: {response.status_code}")

response: <Response [200]>
response.status_code: 200

In [51]:
type(response.text)

str

In [53]:
# Verificar si la solicitud fue exitosa
if response.status_code == 200:
    # Utilizar pandas.read_html para extraer la tabla de la respuesta HTML
    tables = pd.read_html(response.text)
    print(f"El número de tablas encontradas: {len(tables)} \n\n")
else:
    print(f"Error: {response.status_code}")

El número de tablas encontradas: 7

/tmp/ipykernel_22592/2768303041.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(response.text)

In [52]:
io.StringIO(response.text)

In [54]:
# URL de Wikipedia
url = 'https://es.wikipedia.org/wiki/Anexo:%C3%81lbumes_musicales_m%C3%A1s_vendidos#%C3%81lbum_m%C3%A1s_vendido_por_a%C3%B1o_en_todo_el_mundo'

# Simulamos un navegador para evitar el error 403
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) '
                  'AppleWebKit/537.36 (KHTML, like Gecko) '
                  'Chrome/123.0 Safari/537.36'
}

# Realizar la solicitud GET con el User-Agent especificado
response = requests.get(url, headers=headers)

if response.status_code == 200:
    # Convertir el HTML en un archivo de html
    html_content = io.StringIO(response.text)

    # Extraer tablas sin warning
    tables = pd.read_html(html_content)

    print(f"El número de tablas encontradas: {len(tables)} \n")
else:
    print(f"Error: {response.status_code}")

El número de tablas encontradas: 7

In [55]:
type(tables)

list

In [56]:
# Mostramos la primera tabla
display(tables[0].head())

                     0
0     Álbum de estudio
1  Álbum recopilatorio
2         Banda sonora
3        Álbum en vivo

In [60]:
#Buscamos la tabla que necesitamos

url = 'https://es.wikipedia.org/wiki/Anexo:%C3%81lbumes_musicales_m%C3%A1s_vendidos#%C3%81lbum_m%C3%A1s_vendido_por_a%C3%B1o_en_todo_el_mundo'

# Simulamos un navegador para evitar el error 403
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) '
                  'AppleWebKit/537.36 (KHTML, like Gecko) '
                  'Chrome/123.0 Safari/537.36'
}

# Realizar la solicitud GET con el User-Agent especificado
response = requests.get(url, headers=headers)

if response.status_code == 200:
    # Convertir el HTML en un archivo de html
    html_content = io.StringIO(response.text)

    # Extraer tablas sin warning
    # # Filtramos las tablas que contienen el texto "Ref" en el encabezado
    tables = pd.read_html(html_content, match='Ref')

    print(f"El número de tablas encontradas: {len(tables)} \n")
else:
    print(f"Error: {response.status_code}")

El número de tablas encontradas: 1

In [61]:
#Esta es la tabla que coincide con lo pedido en el ejercicio

display(tables[0].head())

    Año              Álbum   Artista(s)  Ventas (millones)  Ref(s)
0  2001      Hybrid Theory  Linkin Park                9.0  [191]​
1  2002    The Eminem Show       Eminem               13.9  [192]​
2  2003  Come Away with Me  Norah Jones               11.0  [193]​
3  2004        Confessions        Usher               12.0  [194]​
4  2005                X&Y     Coldplay                8.3  [195]​

In [62]:
#Convertimos a dataframe para poder trabajar con los datos

df_a = tables[0]
df_a

,Año,Álbum,Artista(s),Ventas (millones),Ref(s)
0,2001,Hybrid Theory,Linkin Park,9.00,[191]​
1,2002,The Eminem Show,Eminem,13.90,[192]​
2,2003,Come Away with Me,Norah Jones,11.00,[193]​
3,2004,Confessions,Usher,12.00,[194]​
4,2005,X&Y,Coldplay,8.30,[195]​
5,2006,High School Musical,Artistas varios,7.00,[196]​
6,2007,High School Musical 2,Artistas varios,6.00,[197]​
7,2008,Viva la Vida or Death and All His Friends,Coldplay,6.80,[198]​
8,2009,I Dreamed a Dream,Susan Boyle,8.30,[199]​
9,2010,Recovery,Eminem,5.70,[200]​
10,2011,21,Adele,18.10,[192]​
11,2012,21,Adele,8.30,[201]​
12,2013,Midnight Memories,One Direction,4.00,[202]​
13,2014,Frozen,Artistas varios,10.00,[203]​
14,2015,25,Adele,17.40,[204]​
15,2016,Lemonade,Beyoncé,2.50,[205]​
16,2017,÷,Ed Sheeran,6.10,[206]​
17,2018,The Greatest Showman,Hugh Jackman & artistas varios,3.50,[207]​
18,2019,5x20 All the Best!! 1999–2019,Arashi,3.30,[208]​
19,2020,Map of the Soul: 7,BTS,4.80,[209]​
20,2021,30,Adele,4.68,[210]​
21,2022,Greatest Works of Art,Jay Chou,7.20,[211]​[212]​

In [64]:
#Comprobamos las columnas del df

df_a.columns

Index(['Año', 'Álbum', 'Artista(s)', 'Ventas (millones)', 'Ref(s)'], dtype='object')

In [66]:
#Comprobamos el tipo de datos que tenemos en el df

df_a.dtypes

Año                    int64
Álbum                 object
Artista(s)            object
Ventas (millones)    float64
Ref(s)                object
dtype: object

In [67]:
#Eliminamos las columnas sin información

df_a = df_a.drop(columns=['Ref(s)'])
df_a

,Año,Álbum,Artista(s),Ventas (millones)
0,2001,Hybrid Theory,Linkin Park,9.00
1,2002,The Eminem Show,Eminem,13.90
2,2003,Come Away with Me,Norah Jones,11.00
3,2004,Confessions,Usher,12.00
4,2005,X&Y,Coldplay,8.30
5,2006,High School Musical,Artistas varios,7.00
6,2007,High School Musical 2,Artistas varios,6.00
7,2008,Viva la Vida or Death and All His Friends,Coldplay,6.80
8,2009,I Dreamed a Dream,Susan Boyle,8.30
9,2010,Recovery,Eminem,5.70
10,2011,21,Adele,18.10
11,2012,21,Adele,8.30
12,2013,Midnight Memories,One Direction,4.00
13,2014,Frozen,Artistas varios,10.00
14,2015,25,Adele,17.40
15,2016,Lemonade,Beyoncé,2.50
16,2017,÷,Ed Sheeran,6.10
17,2018,The Greatest Showman,Hugh Jackman & artistas varios,3.50
18,2019,5x20 All the Best!! 1999–2019,Arashi,3.30
19,2020,Map of the Soul: 7,BTS,4.80
20,2021,30,Adele,4.68
21,2022,Greatest Works of Art,Jay Chou,7.20

In [69]:
#Cambiamos el tipo de número en la columna de ventas

df_a['Ventas (millones)'] = df_a['Ventas (millones)'].astype(float) * 1_000_000
df_a

,Año,Álbum,Artista(s),Ventas (millones)
0,2001,Hybrid Theory,Linkin Park,9000000.0
1,2002,The Eminem Show,Eminem,13900000.0
2,2003,Come Away with Me,Norah Jones,11000000.0
3,2004,Confessions,Usher,12000000.0
4,2005,X&Y,Coldplay,8300000.0
5,2006,High School Musical,Artistas varios,7000000.0
6,2007,High School Musical 2,Artistas varios,6000000.0
7,2008,Viva la Vida or Death and All His Friends,Coldplay,6800000.0
8,2009,I Dreamed a Dream,Susan Boyle,8300000.0
9,2010,Recovery,Eminem,5700000.0
10,2011,21,Adele,18100000.0
11,2012,21,Adele,8300000.0
12,2013,Midnight Memories,One Direction,4000000.0
13,2014,Frozen,Artistas varios,10000000.0
14,2015,25,Adele,17400000.0
15,2016,Lemonade,Beyoncé,2500000.0
16,2017,÷,Ed Sheeran,6100000.0
17,2018,The Greatest Showman,Hugh Jackman & artistas varios,3500000.0
18,2019,5x20 All the Best!! 1999–2019,Arashi,3300000.0
19,2020,Map of the Soul: 7,BTS,4800000.0
20,2021,30,Adele,4680000.0
21,2022,Greatest Works of Art,Jay Chou,7200000.0

In [70]:
#Renombramos las columnas para que sean más claras

df_a = df_a.rename(columns={
    'Ventas (millones)​': 'ventas'
})

In [71]:
df_a

,Año,Álbum,Artista(s),Ventas (millones)
0,2001,Hybrid Theory,Linkin Park,9000000.0
1,2002,The Eminem Show,Eminem,13900000.0
2,2003,Come Away with Me,Norah Jones,11000000.0
3,2004,Confessions,Usher,12000000.0
4,2005,X&Y,Coldplay,8300000.0
5,2006,High School Musical,Artistas varios,7000000.0
6,2007,High School Musical 2,Artistas varios,6000000.0
7,2008,Viva la Vida or Death and All His Friends,Coldplay,6800000.0
8,2009,I Dreamed a Dream,Susan Boyle,8300000.0
9,2010,Recovery,Eminem,5700000.0
10,2011,21,Adele,18100000.0
11,2012,21,Adele,8300000.0
12,2013,Midnight Memories,One Direction,4000000.0
13,2014,Frozen,Artistas varios,10000000.0
14,2015,25,Adele,17400000.0
15,2016,Lemonade,Beyoncé,2500000.0
16,2017,÷,Ed Sheeran,6100000.0
17,2018,The Greatest Showman,Hugh Jackman & artistas varios,3500000.0
18,2019,5x20 All the Best!! 1999–2019,Arashi,3300000.0
19,2020,Map of the Soul: 7,BTS,4800000.0
20,2021,30,Adele,4680000.0
21,2022,Greatest Works of Art,Jay Chou,7200000.0

## 🎈 3. Ejercicio beautiful soup🎈

- Beautiful Soup: scrapear la tabla de lenguajes de programación más utilizados (https://www.tiobe.com/tiobe-index/) creando un dataframe con una columna llamada "lenguaje" y otra columna llamada "porcentaje_uso" (cogiendo la info de programming language y ratings respectivamente).

In [114]:
from bs4 import BeautifulSoup as bs
import requests
import pandas as pd

In [115]:
# URL
url = 'https://www.tiobe.com/tiobe-index/'

# Simulamos un navegador para evitar el error 403
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) '
                  'AppleWebKit/537.36 (KHTML, like Gecko) '
                  'Chrome/123.0 Safari/537.36'
}

# Realizar la solicitud GET con el User-Agent especificado
response = requests.get(url, headers=headers)

if response.status_code == 200:
    print(f"status_code: {response.status_code}")
    # Convertir el HTML en un archivo de html
    soup = bs(response.text, 'html.parser')
else:
    print(f"Error: {response.status_code}")

status_code: 200

In [116]:
# soup es un tipo de dato propio de bs
# representa un HTML parseado
type(soup)

bs4.BeautifulSoup

In [117]:
soup.prettify()

'<!DOCTYPE html>\n<html lang="en-US">\n <head>\n  <meta charset="utf-8"/>\n  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>\n  <title>\n   TIOBE Index - TIOBE\n  </title>\n  <link href="http://gmpg.org/xfn/11" rel="profile"/>\n  <link href="https://www.tiobe.com/wp-content/themes/tiobe/style.css" media="screen" rel="stylesheet" type="text/css"/>\n  <link href="https://www.tiobe.com/xmlrpc.php" rel="pingback"/>\n  <link href="https://www.tiobe.com/wp-content/themes/tiobe/favicon/apple-touch-icon.png" rel="apple-touch-icon" sizes="180x180"/>\n  <link href="https://www.tiobe.com/wp-content/themes/tiobe/favicon/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png"/>\n  <link href="https://www.tiobe.com/wp-content/themes/tiobe/favicon/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png"/>\n  <link href="https://www.tiobe.com/wp-content/themes/tiobe/favicon/site.webmanifest" rel="manifest"/>\n  <link color="#287ac8" href="https://www.tiobe.com/wp-content/themes/tiobe/favicon/safari-pinned-tab.svg" rel="mask-icon"/>\n  <link href="https://www.tiobe.com/wp-content/themes/tiobe/favicon/favicon.ico" rel="shortcut icon"/>\n  <meta content="#ffffff" name="msapplication-TileColor"/>\n  <meta content="https://www.tiobe.com/wp-content/themes/tiobe/favicon/browserconfig.xml" name="msapplication-config"/>\n  <meta content="#ffffff" name="theme-color"/>\n  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\n  <!--[if lt IE 9]>\n\t<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>\n\t<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>\n\t<![endif]-->\n  <script type="text/javascript">\n   window.dataLayer = window.dataLayer || [];\n\n\tfunction gtag() {\n\t\tdataLayer.push(arguments);\n\t}\n\n\tgtag("consent", "default", {\n\t\tad_personalization: "denied",\n\t\tad_storage: "denied",\n\t\tad_user_data: "denied",\n\t\tanalytics_storage: "denied",\n\t\tfunctionality_storage: "denied",\n\t\tpersonalization_storage: "denied",\n\t\tsecurity_storage: "granted",\n\t\twait_for_update: 500,\n\t});\n\tgtag("set", "ads_data_redaction", true);\n  </script>\n  <script type="text/javascript">\n   (function (w, d, s, l, i) {\n\t\tw[l] = w[l] || [];\n\t\tw[l].push({\'gtm.start\': new Date().getTime(), event: \'gtm.js\'});\n\t\tvar f = d.getElementsByTagName(s)[0], j = d.createElement(s), dl = l !== \'dataLayer\' ? \'&l=\' + l : \'\';\n\t\tj.async = true;\n\t\tj.src = \'https://www.googletagmanager.com/gtm.js?id=\' + i + dl;\n\t\tf.parentNode.insertBefore(j, f);\n\t})(\n\t\twindow,\n\t\tdocument,\n\t\t\'script\',\n\t\t\'dataLayer\',\n\t\t\'GTM-P5LV767\'\n\t);\n  </script>\n  <script async="" data-cbid="d715952c-d0b8-4f9e-afee-b0da55c6f179" data-culture="EN" data-implementation="wp" id="Cookiebot" src="https://consent.cookiebot.com/uc.js" type="text/javascript">\n  </script>\n  <meta content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1" name="robots">\n   <!-- This site is optimized with the Yoast SEO plugin v27.0 - https://yoast.com/product/yoast-seo-wordpress/ -->\n   <link href="https://www.tiobe.com/tiobe-index/" rel="canonical">\n    <meta content="en_US" property="og:locale">\n     <meta content="article" property="og:type">\n      <meta content="TIOBE Index - TIOBE" property="og:title"/>\n      <meta content="https://www.tiobe.com/tiobe-index/" property="og:url"/>\n      <meta content="TIOBE" property="og:site_name"/>\n      <meta content="2022-06-03T14:27:04+00:00" property="article:modified_time"/>\n      <meta content="summary_large_image" name="twitter:card"/>\n      <meta content="Est. reading time" name="twitter:label1"/>\n      <meta content="3 minutes" name="twitter:data1"/>\n      <script class="yoast-schema-graph" type="application/ld+json">\n       {"@context":"https://schema.org","@graph":[{"@type":"WebPage","@id":"https://www.tiobe.com/tiobe-index/","url":"https://www.tiobe.com/tiobe-index/","name":"TIOBE Index - TIOBE","isPartOf":{"@id":"https://www.tiobe.com/#website"},"datePublished":"2021-12-27T15:46:12+00:00","dateModified":"2022-06-03T14:27:04+00:00","description":"TIOBE index programming languages describes the monthly ranking of programming languages on popularity. Top 3 is Python, C, Java","breadcrumb":{"@id":"https://www.tiobe.com/tiobe-index/#breadcrumb"},"inLanguage":"en-US","potentialAction":[{"@type":"ReadAction","target":["https://www.tiobe.com/tiobe-index/"]}]},{"@type":"BreadcrumbList","@id":"https://www.tiobe.com/tiobe-index/#breadcrumb","itemListElement":[{"@type":"ListItem","position":1,"name":"Home","item":"https://www.tiobe.com/"},{"@type":"ListItem","position":2,"name":"TIOBE Index"}]},{"@type":"WebSite","@id":"https://www.tiobe.com/#website","url":"https://www.tiobe.com/","name":"TIOBE","description":"","potentialAction":[{"@type":"SearchAction","target":{"@type":"EntryPoint","urlTemplate":"https://www.tiobe.com/?s={search_term_string}"},"query-input":{"@type":"PropertyValueSpecification","valueRequired":true,"valueName":"search_term_string"}}],"inLanguage":"en-US"}]}\n      </script>\n      <!-- / Yoast SEO plugin. -->\n      <link href="//code.highcharts.com" rel="dns-prefetch">\n       <style id="wp-img-auto-sizes-contain-inline-css">\n        img:is([sizes=auto i],[sizes^="auto," i]){contain-intrinsic-size:3000px 1500px}\n/*# sourceURL=wp-img-auto-sizes-contain-inline-css */\n       </style>\n       <style id="classic-theme-styles-inline-css">\n        /*! This file is auto-generated */\n.wp-block-button__link{color:#fff;background-color:#32373c;border-radius:9999px;box-shadow:none;text-decoration:none;padding:calc(.667em + 2px) calc(1.333em + 2px);font-size:1.125em}.wp-block-file__button{background:#32373c;color:#fff;text-decoration:none}\n/*# sourceURL=/wp-includes/css/classic-themes.min.css */\n       </style>\n       <link href="https://www.tiobe.com/wp-content/themes/tiobe/css/plugins.min.css?ver=6.9.4" id="Css-plugins-css" media="all" rel="stylesheet">\n        <link href="https://www.tiobe.com/wp-content/uploads/wp-less/tiobe/css/style-27410e71f8.css" id="Less-Stylesheet-css" media="all" rel="stylesheet">\n         <script id="jQuery-root-js" src="https://www.tiobe.com/wp-content/themes/tiobe/js/jquery.min.js?ver=1.0.0">\n         </script>\n         <script id="highcharts-js" src="//code.highcharts.com/highcharts.js?ver=1.0.0">\n         </script>\n         <link href="https://fonts.googleapis.com" rel="preconnect"/>\n         <link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>\n         <link href="https://fonts.googleapis.com/css2?family=Titillium+Web:wght@600;700&amp;family=Work+Sans:wght@400;500;600;700&amp;display=block" rel="stylesheet"/>\n         <link href="https://www.tiobe.com/wp-content/uploads/2022/06/cropped-android-chrome-512x512-1-32x32.png" rel="icon" sizes="32x32">\n          <link href="https://www.tiobe.com/wp-content/uploads/2022/06/cropped-android-chrome-512x512-1-192x192.png" rel="icon" sizes="192x192">\n           <link href="https://www.tiobe.com/wp-content/uploads/2022/06/cropped-android-chrome-512x512-1-180x180.png" rel="apple-touch-icon">\n            <meta content="https://www.tiobe.com/wp-content/uploads/2022/06/cropped-android-chrome-512x512-1-270x270.png" name="msapplication-TileImage"/>\n           </link>\n          </link>\n         </link>\n        </link>\n       </link>\n      </link>\n     </meta>\n    </meta>\n   </link>\n  </meta>\n </head>\n <body class="wp-singular page-template page-template-page-index page-template-page-index-php page page-id-1182 wp-theme-tiobe kleine-golf">\n  <div id="old-ie-banner">\n   <div class="container">\n    <p>\n     <b>\n      Let op!\n     </b>\n     Internet Explorer wordt niet meer ondersteund. Hierdoor kan de website mogelijk niet goed functioneren, gebruik een alternatieve browser om optimaal gebruik te maken van deze website.\n     <a class="text-link" href="http://outdatedbrowser.com/nl" target="_blank">\n      Klik hier om een alternatieve browser te downloaden\n     </a>\n     .\n    </p>\n   </div>\n  </div>\n  <header>\n   <!--Start Header-->\n   <div class="header-top">\n    <div class="container">\n     <div class="header-inner">\n      <div class="logo">\n       <a aria-label="TIOBE Software BV" class="logolink" href="https://www.tiobe.com">\n        <img alt="TIOBE the software quality company logo" src="https://www.tiobe.com/wp-content/uploads/2021/11/logo-tiobe.svg"/>\n       </a>\n      </div>\n      <div class="navigation">\n       <div class="top-nav d-none d-lg-flex">\n        <ul class="menu" id="menu-top-menu">\n         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1045" id="menu-item-1045">\n          <a href="https://www.tiobe.com/about-us/">\n           About us\n          </a>\n         </li>\n         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2731" id="menu-item-2731">\n          <a href="https://www.tiobe.com/knowledge/">\n           Knowledge\n          </a>\n         </li>\n         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1044" id="menu-item-1044">\n          <a href="https://www.tiobe.com/news/">\n           News\n          </a>\n         </li>\n         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1042" id="menu-item-1042">\n          <a href="https://www.tiobe.com/coding-standards/">\n           Coding Standards\n          </a>\n         </li>\n         <li class="menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item page-item-1182 current_page_item menu-item-1184" id="menu-item-1184">\n          <a aria-current="page" href="https://www.tiobe.com/tiobe-index/">\n           TIOBE Index\n          </a>\n         </li>\n         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1046" id="menu-item-1046">\n          <a href="https://www.tiobe.com/contact/">\n           Contact\n          </a>\n         </li>\n        </ul>\n        <a class="search-trigger" href="#">\n        </a>\n       </div>\n       <nav class="nav d-none d-md-flex">\n        <ul class="menu" id="menu-hoofdmenu">\n         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-1049" id="menu-item-1049">\n          <a href="https://www.tiobe.com/products/">\n           Products\n          </a>\n          <ul class="sub-menu">\n           <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1159" id="menu-item-1159">\n            <a href="https://www.tiobe.com/products/tics/">\n             TiCS Framework\n            </a>\n           </li>\n           <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1334" id="menu-item-1334">\n            <a href="https://www.tiobe.com/products/tics-fact-sheet/">\n             TiCS Fact Sheet\n            </a>\n           </li>\n           <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1176" id="menu-item-1176">\n            <a href="https://www.tiobe.com/products/tqi-quality-assessment/">\n             TQI Code Quality Assessment\n            </a>\n           </li>\n           <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1177" id="menu-item-1177">\n            <a href="https://www.tiobe.com/products/tpm-maintainability-assessment/">\n             Trusted Product Maintainability Assessment\n            </a>\n           </li>\n          </ul>\n         </li>\n         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-1162" id="menu-item-1162">\n          <a href="https://www.tiobe.com/quality-models/">\n           Quality Models\n          </a>\n          <ul class="sub-menu">\n           <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1171" id="menu-item-1171">\n            <a href="https://www.tiobe.com/quality-models/tqi/">\n             TIOBE Quality Indicator\n            </a>\n           </li>\n           <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1170" id="menu-item-1170">\n            <a href="https://www.tiobe.com/quality-models/trusted-product-maintainability/">\n             Trusted Product Maintainability\n            </a>\n           </li>\n          </ul>\n         </li>\n         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-1047" id="menu-item-1047">\n          <a href="https://www.tiobe.com/markets/">\n           Markets\n          </a>\n          <ul class="sub-menu">\n           <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1166" id="menu-item-1166">\n            <a href="https://www.tiobe.com/markets/customers/">\n             Customers\n            </a>\n           </li>\n           <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1163" id="menu-item-1163">\n            <a href="https://www.tiobe.com/markets/distributors/">\n             Distributors\n            </a>\n           </li>\n           <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2606" id="menu-item-2606">\n            <a href="https://www.tiobe.com/markets/partners/">\n             Partners\n            </a>\n           </li>\n          </ul>\n         </li>\n        </ul>\n        <a class="button d-none d-md-inline-block small white highlight" href="https://www.tiobe.com/request-a-demo/" rel="" target="_self">\n         Schedule a demo\n        </a>\n       </nav>\n       <a class="search-trigger d-none d-md-inline-block d-lg-none" href="#">\n       </a>\n       <div class="nav-toggle d-block d-lg-none">\n        <div class="hamburger-menu">\n         <div class="menu-part">\n         </div>\n         <div class="menu-part">\n         </div>\n         <div class="menu-part">\n         </div>\n        </div>\n       </div>\n      </div>\n     </div>\n     <div class="search-bar-item">\n      <div class="search-bar-item-inner">\n       <div class="container">\n        <form action="https://www.tiobe.com/" class="searchform" method="get" role="search">\n         <input class="search-field" name="s" placeholder="Start typing to search" type="text" value=""/>\n         <div class="submit-container">\n          <input class="search-button button blue dark small search-icon" type="submit" value="Search"/>\n         </div>\n        </form>\n       </div>\n      </div>\n     </div>\n    </div>\n   </div>\n  </header>\n  <section class="website-content">\n   <div class="tiobe-index container">\n    <article class="content">\n     <p id="breadcrumbs">\n      <span>\n       <span>\n        <a href="https://www.tiobe.com/">\n         Home\n        </a>\n       </span>\n       »\n       <span aria-current="page" class="breadcrumb_last">\n        <strong>\n         TIOBE Index\n        </strong>\n       </span>\n      </span>\n     </p>\n     <link href="/wp-content/themes/tiobe/tpci/css/tpci.css" rel="stylesheet"/>\n     <style type="text/css">\n      table.table-top20 tbody tr td {\n  vertical-align: baseline;\n}\n\ntd.td-top20 {\n  text-align: center;\n}\n\ntable.table-top20 tbody tr:hover td {\n  background-color: lightgrey;\n\tfont-weight: bold;\n  cursor: pointer;\n  vertical-align: baseline;\n}\n\ntable.table-top20 tbody tr td img {\n    vertical-align: top;\n}\n     </style>\n     <script>\n      $(document).ready(function () {\n$(\'table.table-top20 > tbody > tr\').click(function() {\n  var lang = $(this).find($("td:nth-child(5)")).text();\n  var page = encodeURIComponent(lang);\n  \n  window.open("/tiobe-index/?slug=" + page, "_self");\n  });\n});\n     </script>\n     <script>\n      $(function () {\n  $(\'#container\').highcharts({\n    credits: {\n\t\t  enabled: false\n    },\n    chart: {\n    \ttype: \'spline\'\n    },\n    plotOptions: {\n    \tspline: {\n    \t\tlineWidth: 4,\n    \t\tstates: {\n    \t\t\thover: {\n    \t\t\t\tlineWidth: 5\n    \t\t\t}\n    \t\t},\n    \t\tmarker: {\n    \t\t\tenabled: false\n    \t\t}\n    \t}\n    },\n    title: {\n    \ttext: \'TIOBE Programming Community Index\',\n    \tx: -20,\n    \tuseHTML: true\n    },\n    subtitle: {\n    \ttext: \'Source: www.tiobe.com\',\n    \tx: -20,\n    \tuseHTML: true\n    },\n    xAxis: {\n    \ttype: \'datetime\',\n    \tdateTimeLabelFormats: {\n    \t\tyear: \'%Y\'\n    \t}\n    },\n    yAxis: {\n      min: 0,\n    \ttitle: {\n    \t\ttext: \'Ratings (%)\'\n    \t},\n    \tplotLines: [{\n    \t\tvalue: 0,\n    \t\twidth: 1,\n    \t\tcolor: \'#808080\'\n    \t}]\n    },\n    tooltip: {\n    \tvalueSuffix: \'%\',\n    \tdateTimeLabelFormats: {\n    \t\tweek: "%B %Y"\n    \t}\n    },\n    legend: {\n      align: \'center\',borderWidth: 0,\n    },\n    series: [\n    \t{name : \'Python\',data : [[Date.UTC(2001, 5, 30), 1.25], [Date.UTC(2001, 6, 30), 1.13], [Date.UTC(2001, 7, 30), 1.20], [Date.UTC(2001, 8, 28), 1.17], [Date.UTC(2001, 9, 26), 1.28], [Date.UTC(2001, 10, 28), 1.23], [Date.UTC(2001, 11, 31), 1.04], [Date.UTC(2002, 0, 30), 1.02], [Date.UTC(2002, 1, 27), 0.99], [Date.UTC(2002, 2, 29), 0.99], [Date.UTC(2002, 3, 29), 1.07], [Date.UTC(2002, 4, 29), 1.06], [Date.UTC(2002, 5, 29), 1.13], [Date.UTC(2002, 6, 31), 1.08], [Date.UTC(2002, 7, 29), 1.22], [Date.UTC(2002, 8, 29), 1.08], [Date.UTC(2002, 9, 30), 1.19], [Date.UTC(2002, 10, 29), 1.00], [Date.UTC(2002, 11, 31), 1.00], [Date.UTC(2003, 0, 31), 1.03], [Date.UTC(2003, 1, 28), 0.97], [Date.UTC(2003, 2, 31), 0.99], [Date.UTC(2003, 3, 30), 1.01], [Date.UTC(2003, 4, 30), 1.16], [Date.UTC(2003, 5, 30), 1.28], [Date.UTC(2003, 6, 31), 1.30], [Date.UTC(2003, 7, 31), 1.42], [Date.UTC(2003, 8, 30), 1.49], [Date.UTC(2003, 9, 31), 1.77], [Date.UTC(2003, 10, 30), 1.10], [Date.UTC(2003, 11, 31), 1.13], [Date.UTC(2004, 0, 31), 1.01], [Date.UTC(2004, 1, 29), 1.02], [Date.UTC(2004, 2, 31), 1.01], [Date.UTC(2004, 3, 30), 4.57], [Date.UTC(2004, 4, 30), 6.58], [Date.UTC(2004, 5, 30), 4.96], [Date.UTC(2004, 6, 31), 4.70], [Date.UTC(2004, 7, 30), 5.60], [Date.UTC(2004, 8, 30), 4.44], [Date.UTC(2004, 9, 31), 5.20], [Date.UTC(2004, 10, 30), 3.03], [Date.UTC(2004, 11, 31), 2.84], [Date.UTC(2005, 0, 31), 2.51], [Date.UTC(2005, 1, 28), 2.42], [Date.UTC(2005, 2, 31), 2.70], [Date.UTC(2005, 3, 30), 2.48], [Date.UTC(2005, 4, 31), 2.80], [Date.UTC(2005, 5, 30), 2.52], [Date.UTC(2005, 6, 31), 2.88], [Date.UTC(2005, 7, 31), 3.03], [Date.UTC(2005, 8, 30), 2.88], [Date.UTC(2005, 11, 3), 2.68], [Date.UTC(2006, 0, 4), 2.60], [Date.UTC(2006, 1, 2), 2.67], [Date.UTC(2006, 2, 1), 3.09], [Date.UTC(2006, 3, 2), 2.76], [Date.UTC(2006, 4, 1), 3.04], [Date.UTC(2006, 5, 1), 3.46], [Date.UTC(2006, 6, 2), 3.02], [Date.UTC(2006, 7, 2), 3.07], [Date.UTC(2006, 8, 2), 3.14], [Date.UTC(2006, 9, 1), 3.47], [Date.UTC(2006, 10, 2), 3.64], [Date.UTC(2006, 11, 1), 3.76], [Date.UTC(2007, 0, 2), 3.50], [Date.UTC(2007, 1, 3), 3.57], [Date.UTC(2007, 2, 3), 3.90], [Date.UTC(2007, 3, 1), 3.81], [Date.UTC(2007, 4, 5), 3.78], [Date.UTC(2007, 5, 2), 3.16], [Date.UTC(2007, 6, 2), 3.02], [Date.UTC(2007, 7, 5), 2.75], [Date.UTC(2007, 8, 2), 3.03], [Date.UTC(2007, 9, 4), 3.43], [Date.UTC(2007, 10, 4), 4.23], [Date.UTC(2007, 11, 3), 4.70], [Date.UTC(2008, 0, 3), 5.54], [Date.UTC(2008, 1, 7), 4.76], [Date.UTC(2008, 5, 1), 4.90], [Date.UTC(2008, 6, 2), 4.97], [Date.UTC(2008, 7, 3), 4.98], [Date.UTC(2008, 8, 3), 5.01], [Date.UTC(2008, 9, 6), 4.56], [Date.UTC(2008, 10, 2), 5.14], [Date.UTC(2008, 11, 3), 4.17], [Date.UTC(2009, 0, 2), 4.73], [Date.UTC(2009, 1, 1), 4.57], [Date.UTC(2009, 2, 5), 5.18], [Date.UTC(2009, 3, 7), 6.08], [Date.UTC(2009, 4, 1), 5.55], [Date.UTC(2009, 5, 4), 4.76], [Date.UTC(2009, 6, 2), 4.43], [Date.UTC(2009, 7, 1), 4.49], [Date.UTC(2009, 8, 5), 3.93], [Date.UTC(2009, 9, 2), 3.90], [Date.UTC(2009, 10, 2), 4.67], [Date.UTC(2009, 11, 2), 5.19],

In [118]:
soup

<!DOCTYPE html>

<html lang="en-US">
<head>
<meta charset="utf-8"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<title>TIOBE Index - TIOBE</title>
<link href="http://gmpg.org/xfn/11" rel="profile"/>
<link href="https://www.tiobe.com/wp-content/themes/tiobe/style.css" media="screen" rel="stylesheet" type="text/css"/>
<link href="https://www.tiobe.com/xmlrpc.php" rel="pingback"/>
<link href="https://www.tiobe.com/wp-content/themes/tiobe/favicon/apple-touch-icon.png" rel="apple-touch-icon" sizes="180x180"/>
<link href="https://www.tiobe.com/wp-content/themes/tiobe/favicon/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png"/>
<link href="https://www.tiobe.com/wp-content/themes/tiobe/favicon/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png"/>
<link href="https://www.tiobe.com/wp-content/themes/tiobe/favicon/site.webmanifest" rel="manifest"/>
<link color="#287ac8" href="https://www.tiobe.com/wp-content/themes/tiobe/favicon/safari-pinned-tab.svg" rel="mask-icon"/>
<link href="https://www.tiobe.com/wp-content/themes/tiobe/favicon/favicon.ico" rel="shortcut icon"/>
<meta content="#ffffff" name="msapplication-TileColor"/>
<meta content="https://www.tiobe.com/wp-content/themes/tiobe/favicon/browserconfig.xml" name="msapplication-config"/>
<meta content="#ffffff" name="theme-color"/>
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
	<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
<script type="text/javascript">
	window.dataLayer = window.dataLayer || [];

	function gtag() {
		dataLayer.push(arguments);
	}

	gtag("consent", "default", {
		ad_personalization: "denied",
		ad_storage: "denied",
		ad_user_data: "denied",
		analytics_storage: "denied",
		functionality_storage: "denied",
		personalization_storage: "denied",
		security_storage: "granted",
		wait_for_update: 500,
	});
	gtag("set", "ads_data_redaction", true);
	</script>
<script type="text/javascript">
		(function (w, d, s, l, i) {
		w[l] = w[l] || [];
		w[l].push({'gtm.start': new Date().getTime(), event: 'gtm.js'});
		var f = d.getElementsByTagName(s)[0], j = d.createElement(s), dl = l !== 'dataLayer' ? '&l=' + l : '';
		j.async = true;
		j.src = 'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
		f.parentNode.insertBefore(j, f);
	})(
		window,
		document,
		'script',
		'dataLayer',
		'GTM-P5LV767'
	);
</script>
<script async="" data-cbid="d715952c-d0b8-4f9e-afee-b0da55c6f179" data-culture="EN" data-implementation="wp" id="Cookiebot" src="https://consent.cookiebot.com/uc.js" type="text/javascript"></script>
<meta content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1" name="robots">
<!-- This site is optimized with the Yoast SEO plugin v27.0 - https://yoast.com/product/yoast-seo-wordpress/ -->
<link href="https://www.tiobe.com/tiobe-index/" rel="canonical">
<meta content="en_US" property="og:locale">
<meta content="article" property="og:type">
<meta content="TIOBE Index - TIOBE" property="og:title"/>
<meta content="https://www.tiobe.com/tiobe-index/" property="og:url"/>
<meta content="TIOBE" property="og:site_name"/>
<meta content="2022-06-03T14:27:04+00:00" property="article:modified_time"/>
<meta content="summary_large_image" name="twitter:card"/>
<meta content="Est. reading time" name="twitter:label1"/>
<meta content="3 minutes" name="twitter:data1"/>
<script class="yoast-schema-graph" type="application/ld+json">{"@context":"https://schema.org","@graph":[{"@type":"WebPage","@id":"https://www.tiobe.com/tiobe-index/","url":"https://www.tiobe.com/tiobe-index/","name":"TIOBE Index - TIOBE","isPartOf":{"@id":"https://www.tiobe.com/#website"},"datePublished":"2021-12-27T15:46:12+00:00","dateModified":"2022-06-03T14:27:04+00:00","description":"TIOBE index programming languages describes the monthly ranking of programming languages on popularity. Top 3 is Python, C, Java","breadcrumb":{"@id":"https://www.tiobe.com/tiobe-index/#breadcrumb"},"inLanguage":"en-US","potentialAction":[{"@type":"ReadAction","target":["https://www.tiobe.com/tiobe-index/"]}]},{"@type":"BreadcrumbList","@id":"https://www.tiobe.com/tiobe-index/#breadcrumb","itemListElement":[{"@type":"ListItem","position":1,"name":"Home","item":"https://www.tiobe.com/"},{"@type":"ListItem","position":2,"name":"TIOBE Index"}]},{"@type":"WebSite","@id":"https://www.tiobe.com/#website","url":"https://www.tiobe.com/","name":"TIOBE","description":"","potentialAction":[{"@type":"SearchAction","target":{"@type":"EntryPoint","urlTemplate":"https://www.tiobe.com/?s={search_term_string}"},"query-input":{"@type":"PropertyValueSpecification","valueRequired":true,"valueName":"search_term_string"}}],"inLanguage":"en-US"}]}</script>
<!-- / Yoast SEO plugin. -->
<link href="//code.highcharts.com" rel="dns-prefetch">
<style id="wp-img-auto-sizes-contain-inline-css">
img:is([sizes=auto i],[sizes^="auto," i]){contain-intrinsic-size:3000px 1500px}
/*# sourceURL=wp-img-auto-sizes-contain-inline-css */
</style>
<style id="classic-theme-styles-inline-css">
/*! This file is auto-generated */
.wp-block-button__link{color:#fff;background-color:#32373c;border-radius:9999px;box-shadow:none;text-decoration:none;padding:calc(.667em + 2px) calc(1.333em + 2px);font-size:1.125em}.wp-block-file__button{background:#32373c;color:#fff;text-decoration:none}
/*# sourceURL=/wp-includes/css/classic-themes.min.css */
</style>
<link href="https://www.tiobe.com/wp-content/themes/tiobe/css/plugins.min.css?ver=6.9.4" id="Css-plugins-css" media="all" rel="stylesheet">
<link href="https://www.tiobe.com/wp-content/uploads/wp-less/tiobe/css/style-27410e71f8.css" id="Less-Stylesheet-css" media="all" rel="stylesheet">
<script id="jQuery-root-js" src="https://www.tiobe.com/wp-content/themes/tiobe/js/jquery.min.js?ver=1.0.0"></script>
<script id="highcharts-js" src="//code.highcharts.com/highcharts.js?ver=1.0.0"></script>
<link href="https://fonts.googleapis.com" rel="preconnect"/>
<link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>
<link href="https://fonts.googleapis.com/css2?family=Titillium+Web:wght@600;700&amp;family=Work+Sans:wght@400;500;600;700&amp;display=block" rel="stylesheet"/>
<link href="https://www.tiobe.com/wp-content/uploads/2022/06/cropped-android-chrome-512x512-1-32x32.png" rel="icon" sizes="32x32">
<link href="https://www.tiobe.com/wp-content/uploads/2022/06/cropped-android-chrome-512x512-1-192x192.png" rel="icon" sizes="192x192">
<link href="https://www.tiobe.com/wp-content/uploads/2022/06/cropped-android-chrome-512x512-1-180x180.png" rel="apple-touch-icon">
<meta content="https://www.tiobe.com/wp-content/uploads/2022/06/cropped-android-chrome-512x512-1-270x270.png" name="msapplication-TileImage"/>
</link></link></link></link></link></link></meta></meta></link></meta></head>
<body class="wp-singular page-template page-template-page-index page-template-page-index-php page page-id-1182 wp-theme-tiobe kleine-golf">
<div id="old-ie-banner">
<div class="container">
<p><b>Let op!</b> Internet Explorer wordt niet meer ondersteund. Hierdoor kan de website mogelijk niet goed functioneren, gebruik een alternatieve browser om optimaal gebruik te maken van deze website. <a class="text-link" href="http://outdatedbrowser.com/nl" target="_blank">Klik hier om een alternatieve browser te downloaden</a>.</p>
</div>
</div>
<header>
<!--Start Header-->
<div class="header-top">
<div class="container">
<div class="header-inner">
<div class="logo">
<a aria-label="TIOBE Software BV" class="logolink" href="https://www.tiobe.com"><img alt="TIOBE the software quality company logo" src="https://www.tiobe.com/wp-content/uploads/2021/11/logo-tiobe.svg"/></a> </div>
<div class="navigation">
<div class="top-nav d-none d-lg-flex">
<ul class="menu" id="menu-top-menu"><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1045" id="menu-item-1045"><a href="https://www.tiobe.com/about-us/">About us</a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2731" id="menu-item-2731"><a href="https://www.tiobe.com/knowledge/">Knowledge</a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1044" id="menu-item-1044"><a href="https://www.tiobe.com/news/">News</a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1042" id="menu-item-1042"><a href="https://www.tiobe.com/coding-standards/">Coding Standards</a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item page-item-1182 current_page_item menu-item-1184" id="menu-item-1184"><a aria-current="page" href="https://www.tiobe.com/tiobe-index/">TIOBE Index</a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1046" id="menu-item-1046"><a href="https://www.tiobe.com/contact/">Contact</a></li>
</ul> <a class="search-trigger" href="#"></a>
</div>
<nav class="nav d-none d-md-flex">
<ul class="menu" id="menu-hoofdmenu"><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-1049" id="menu-item-1049"><a href="https://www.tiobe.com/products/">Products</a>
<ul class="sub-menu">
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1159" id="menu-item-1159"><a href="https://www.tiobe.com/products/tics/">TiCS Framework</a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1334" id="menu-item-1334"><a href="https://www.tiobe.com/products/tics-fact-sheet/">TiCS Fact Sheet</a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1176" id="menu-item-1176"><a href="https://www.tiobe.com/products/tqi-quality-assessment/">TQI Code Quality Assessment</a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1177" id="menu-item-1177"><a href="https://www.tiobe.com/products/tpm-maintainability-assessment/">Trusted Product Maintainability Assessment</a></li>
</ul>
</li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-1162" id="menu-item-1162"><a href="https://www.tiobe.com/quality-models/">Quality Models</a>
<ul class="sub-menu">
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1171" id="menu-item-1171"><a href="https://www.tiobe.com/quality-models/tqi/">TIOBE Quality Indicator</a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1170" id="menu-item-1170"><a href="https://www.tiobe.com/quality-models/trusted-product-maintainability/">Trusted Product Maintainability</a></li>
</ul>
</li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-1047" id="menu-item-1047"><a href="https://www.tiobe.com/markets/">Markets</a>
<ul class="sub-menu">
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1166" id="menu-item-1166"><a href="https://www.tiobe.com/markets/customers/">Customers</a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1163" id="menu-item-1163"><a href="https://www.tiobe.com/markets/distributors/">Distributors</a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2606" id="menu-item-2606"><a href="https://www.tiobe.com/markets/partners/">Partners</a></li>
</ul>
</li>
</ul> <a class="button d-none d-md-inline-block small white highlight" href="https://www.tiobe.com/request-a-demo/" rel="" target="_self">Schedule a demo</a>
</nav>
<a class="search-trigger d-none d-md-inline-block d-lg-none" href="#"></a>
<div class="nav-toggle d-block d-lg-none">
<div class="hamburger-menu">
<div class="menu-part"></div>
<div class="menu-part"></div>
<div class="menu-part"></div>
</div>
</div>
</div>
</div>
<div class="search-bar-item">
<div class="search-bar-item-inner">
<div class="container">
<form action="https://www.tiobe.com/" class="searchform" method="get" role="search">
<input class="search-field" name="s" placeholder="Start typing to search" type="text" value=""/>
<div class="submit-container">
<input class="search-button button blue dark small search-icon" type="submit" value="Search"/>
</div>
</form> </div>
</div>
</div>
</div>
</div>
</header>
<section class="website-content">
<div class="tiobe-index container">
<article class="content">
<p id="breadcrumbs"><span><span><a href="https://www.tiobe.com/">Home</a></span> » <span aria-current="page" class="breadcrumb_last"><strong>TIOBE Index</strong></span></span></p> <link href="/wp-content/themes/tiobe/tpci/css/tpci.css" rel="stylesheet"/>
<style type="text/css">
table.table-top20 tbody tr td {
  vertical-align: baseline;
}

td.td-top20 {
  text-align: center;
}

table.table-top20 tbody tr:hover td {
  background-color: lightgrey;
	font-weight: bold;
  cursor: pointer;
  vertical-align: baseline;
}

table.table-top20 tbody tr td img {
    vertical-align: top;
}
</style>
<script>
$(document).ready(function () {
$('table.table-top20 > tbody > tr').click(function() {
  var lang = $(this).find($("td:nth-child(5)")).text();
  var page = encodeURIComponent(lang);

  window.open("/tiobe-index/?slug=" + page, "_self");
  });
});
</script>
<script>$(function () {
  $('#container').highcharts({
    credits: {
		  enabled: false
    },
    chart: {
    	type: 'spline'
    },
    plotOptions: {
    	spline: {
    		lineWidth: 4,
    		states: {
    			hover: {
    				lineWidth: 5
    			}
    		},
    		marker: {
    			enabled: false
    		}
    	}
    },
    title: {
    	text: 'TIOBE Programming Community Index',
    	x: -20,
    	useHTML: true
    },
    subtitle: {
    	text: 'Source: www.tiobe.com',
    	x: -20,
    	useHTML: true
    },
    xAxis: {
    	type: 'datetime',
    	dateTimeLabelFormats: {
    		year: '%Y'
    	}
    },
    yAxis: {
      min: 0,
    	title: {
    		text: 'Ratings (%)'
    	},
    	plotLines: [{
    		value: 0,
    		width: 1,
    		color: '#808080'
    	}]
    },
    tooltip: {
    	valueSuffix: '%',
    	dateTimeLabelFormats: {
    		week: "%B %Y"
    	}
    },
    legend: {
      align: 'center',borderWidth: 0,
    },
    series: [

In [119]:
tables = soup.find_all('table')

In [120]:
type(tables)

bs4.element.ResultSet

In [121]:
len(tables)

4

In [122]:
# Buscar la tabla específica basada en el caption
# Utilizamos soup.find_all para encontrar todas las tablas (<table>)
#  que tienen la clase 'table-top20' en el documento HTML
# filtrando por la clase se reduce el numero de coincidencias
tables = soup.find_all('table', {'class': 'table-top20'})

print(f"Hemos encontrado {len(tables)} tablas que tienen en la clase 'table-top20' en nuestro documento HTML ")

print(f"\nSi no filtráramos por la clase, encontraríamos {len(soup.find_all('table'))} tablas en nuestro documento HTML ")

Hemos encontrado 1 tablas que tienen en la clase 'table-top20' en nuestro documento HTML

Si no filtráramos por la clase, encontraríamos 4 tablas en nuestro documento HTML

In [123]:
import pandas as pd

df_p = pd.read_html(str(tables[0]))[0]
df_p

/tmp/ipykernel_22592/151933729.py:3: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_p = pd.read_html(str(tables[0]))[0]

,Mar 2026,Mar 2025,Change,Programming Language,Programming Language.1,Ratings,Change.1
0,1,1,NaN,NaN,Python,21.25%,-2.59%
1,2,4,NaN,NaN,C,11.55%,+2.02%
2,3,2,NaN,NaN,C++,8.18%,-2.90%
3,4,3,NaN,NaN,Java,7.99%,-2.37%
4,5,5,NaN,NaN,C#,6.36%,+1.49%
5,6,6,NaN,NaN,JavaScript,3.45%,-0.01%
6,7,9,NaN,NaN,Visual Basic,2.50%,-0.02%
7,8,8,NaN,NaN,SQL,2.00%,-0.57%
8,9,16,NaN,NaN,R,1.88%,+0.94%
9,10,10,NaN,NaN,Delphi/Object Pascal,1.80%,-0.36%
10,11,24,NaN,NaN,Perl,1.75%,+1.05%
11,12,12,NaN,NaN,Scratch,1.63%,-0.03%
12,13,11,NaN,NaN,Fortran,1.45%,-0.25%
13,14,14,NaN,NaN,Rust,1.31%,+0.09%
14,15,15,NaN,NaN,MATLAB,1.29%,+0.31%
15,16,7,NaN,NaN,Go,1.29%,-1.49%
16,17,17,NaN,NaN,Assembly language,1.29%,+0.42%
17,18,13,NaN,NaN,PHP,1.23%,-0.25%
18,19,18,NaN,NaN,Ada,1.10%,+0.25%
19,20,26,NaN,NaN,Swift,1.04%,+0.44%

In [124]:
df_p.head()
df_p.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Mar 2026                20 non-null     int64
 1   Mar 2025                20 non-null     int64
 2   Change                  0 non-null      float64
 3   Programming Language    0 non-null      float64
 4   Programming Language.1  20 non-null     object
 5   Ratings                 20 non-null     object
 6   Change.1                20 non-null     object
dtypes: float64(2), int64(2), object(3)
memory usage: 1.2+ KB

In [125]:
df_p.columns

Index(['Mar 2026', 'Mar 2025', 'Change', 'Programming Language',
       'Programming Language.1', 'Ratings', 'Change.1'],
      dtype='object')

In [126]:
df_p = df_p.drop(columns=['Programming Language', 'Change'])
df_p

    Mar 2026  Mar 2025 Programming Language.1 Ratings Change.1
0          1         1                 Python  21.25%   -2.59%
1          2         4                      C  11.55%   +2.02%
2          3         2                    C++   8.18%   -2.90%
3          4         3                   Java   7.99%   -2.37%
4          5         5                     C#   6.36%   +1.49%
5          6         6             JavaScript   3.45%   -0.01%
6          7         9           Visual Basic   2.50%   -0.02%
7          8         8                    SQL   2.00%   -0.57%
8          9        16                      R   1.88%   +0.94%
9         10        10   Delphi/Object Pascal   1.80%   -0.36%
10        11        24                   Perl   1.75%   +1.05%
11        12        12                Scratch   1.63%   -0.03%
12        13        11                Fortran   1.45%   -0.25%
13        14        14                   Rust   1.31%   +0.09%
14        15        15                 MATLAB   1.29%   +0.31%
15        16         7                     Go   1.29%   -1.49%
16        17        17      Assembly language   1.29%   +0.42%
17        18        13                    PHP   1.23%   -0.25%
18        19        18                    Ada   1.10%   +0.25%
19        20        26                  Swift   1.04%   +0.44%

In [127]:
df_p = df_p.rename(columns={
    'Programming Language.1​': 'lenguaje',
    'Ratings': 'porcentaje_uso'
})

In [128]:
df_p

    Mar 2026  Mar 2025 Programming Language.1 porcentaje_uso Change.1
0          1         1                 Python         21.25%   -2.59%
1          2         4                      C         11.55%   +2.02%
2          3         2                    C++          8.18%   -2.90%
3          4         3                   Java          7.99%   -2.37%
4          5         5                     C#          6.36%   +1.49%
5          6         6             JavaScript          3.45%   -0.01%
6          7         9           Visual Basic          2.50%   -0.02%
7          8         8                    SQL          2.00%   -0.57%
8          9        16                      R          1.88%   +0.94%
9         10        10   Delphi/Object Pascal          1.80%   -0.36%
10        11        24                   Perl          1.75%   +1.05%
11        12        12                Scratch          1.63%   -0.03%
12        13        11                Fortran          1.45%   -0.25%
13        14        14                   Rust          1.31%   +0.09%
14        15        15                 MATLAB          1.29%   +0.31%
15        16         7                     Go          1.29%   -1.49%
16        17        17      Assembly language          1.29%   +0.42%
17        18        13                    PHP          1.23%   -0.25%
18        19        18                    Ada          1.10%   +0.25%
19        20        26                  Swift          1.04%   +0.44%

In [129]:
print(df_p.columns.tolist())

['Mar 2026', 'Mar 2025', 'Programming Language.1', 'porcentaje_uso', 'Change.1']

In [130]:
df_p.columns = (
    df_p.columns
    .str.strip()
    .str.replace('\u200b','')
)

In [131]:
df_p = df_p.rename(columns={
    'Programming Language.1​': 'lenguaje'
})

In [132]:
df_p

    Mar 2026  Mar 2025 Programming Language.1 porcentaje_uso Change.1
0          1         1                 Python         21.25%   -2.59%
1          2         4                      C         11.55%   +2.02%
2          3         2                    C++          8.18%   -2.90%
3          4         3                   Java          7.99%   -2.37%
4          5         5                     C#          6.36%   +1.49%
5          6         6             JavaScript          3.45%   -0.01%
6          7         9           Visual Basic          2.50%   -0.02%
7          8         8                    SQL          2.00%   -0.57%
8          9        16                      R          1.88%   +0.94%
9         10        10   Delphi/Object Pascal          1.80%   -0.36%
10        11        24                   Perl          1.75%   +1.05%
11        12        12                Scratch          1.63%   -0.03%
12        13        11                Fortran          1.45%   -0.25%
13        14        14                   Rust          1.31%   +0.09%
14        15        15                 MATLAB          1.29%   +0.31%
15        16         7                     Go          1.29%   -1.49%
16        17        17      Assembly language          1.29%   +0.42%
17        18        13                    PHP          1.23%   -0.25%
18        19        18                    Ada          1.10%   +0.25%
19        20        26                  Swift          1.04%   +0.44%

In [133]:
col_old = [c for c in df_p.columns if 'Programming Language' in c][0]
df_p = df_p.rename(columns={col_old: 'lenguaje'})

In [134]:
df_p

    Mar 2026  Mar 2025              lenguaje porcentaje_uso Change.1
0          1         1                Python         21.25%   -2.59%
1          2         4                     C         11.55%   +2.02%
2          3         2                   C++          8.18%   -2.90%
3          4         3                  Java          7.99%   -2.37%
4          5         5                    C#          6.36%   +1.49%
5          6         6            JavaScript          3.45%   -0.01%
6          7         9          Visual Basic          2.50%   -0.02%
7          8         8                   SQL          2.00%   -0.57%
8          9        16                     R          1.88%   +0.94%
9         10        10  Delphi/Object Pascal          1.80%   -0.36%
10        11        24                  Perl          1.75%   +1.05%
11        12        12               Scratch          1.63%   -0.03%
12        13        11               Fortran          1.45%   -0.25%
13        14        14                  Rust          1.31%   +0.09%
14        15        15                MATLAB          1.29%   +0.31%
15        16         7                    Go          1.29%   -1.49%
16        17        17     Assembly language          1.29%   +0.42%
17        18        13                   PHP          1.23%   -0.25%
18        19        18                   Ada          1.10%   +0.25%
19        20        26                 Swift          1.04%   +0.44%

In [135]:
#Eliminamos las columnas para obtener df final

df_p = df_p.drop(columns=['Mar 2026', 'Mar 2025', 'Change.1'])
df_p

                lenguaje porcentaje_uso
0                 Python         21.25%
1                      C         11.55%
2                    C++          8.18%
3                   Java          7.99%
4                     C#          6.36%
5             JavaScript          3.45%
6           Visual Basic          2.50%
7                    SQL          2.00%
8                      R          1.88%
9   Delphi/Object Pascal          1.80%
10                  Perl          1.75%
11               Scratch          1.63%
12               Fortran          1.45%
13                  Rust          1.31%
14                MATLAB          1.29%
15                    Go          1.29%
16     Assembly language          1.29%
17                   PHP          1.23%
18                   Ada          1.10%
19                 Swift          1.04%